language: objective-c
osx_image: xcode8.3
script: xcodebuild clean && xcodebuild build && xcodebuild test -project Project.xcodeproj -scheme Project -destination "platform=iOS Simulator,name=iPhone 7,OS=latest" CODE_SIGNING_REQUIRED=NO
